env: "local"
font_path: "./fonts/UbuntuMono-Regular.ttf"
font_size: 64
max_width: 1000

bot_token: 6373411772:AAEztDiruIYuR2eMaXDRj3f1_GdeIu2Ujp4
bot_storage_chat_id: -807726320

video_options:
  random_delay: true
  min_delay: 0.2
  max_delay: 0.3
  delay: 0.5
  fps: 5